use std::env;
use std::fs;
use std::path::PathBuf;

fn read_dimension(source: &str, function: &str) -> usize {
    let marker = format!("export i32 {}()", function);
    let start = source
        .find(&marker)
        .unwrap_or_else(|| panic!("display_config.mln is missing {}()", function));
    let body = &source[start..];
    let return_start = body
        .find("return")
        .unwrap_or_else(|| panic!("{}() must return a positive integer", function));
    let digits = body[return_start + "return".len()..]
        .trim_start()
        .chars()
        .take_while(|ch| ch.is_ascii_digit())
        .collect::<String>();
    let value = digits
        .parse::<usize>()
        .unwrap_or_else(|_| panic!("{}() must return a positive integer", function));
    assert!(value > 0, "{}() must return a positive integer", function);
    value
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let config_path = manifest_dir.join("../../system/MyOS/src/ui/display_config.mln");
    println!("cargo:rerun-if-changed={}", config_path.display());

    let source = fs::read_to_string(&config_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {}", config_path.display(), err));
    let width = read_dimension(&source, "width");
    let height = read_dimension(&source, "height");
    let pixels = width
        .checked_mul(height)
        .expect("display dimensions overflow pixel count");
    let bytes = pixels
        .checked_mul(4)
        .expect("display dimensions overflow framebuffer size");
    assert!(
        bytes <= u32::MAX as usize,
        "framebuffer must fit in the 32-bit address space"
    );

    let generated = format!(
        "// Generated by build.rs from {}. Do not edit.\n\
         pub const DISPLAY_WIDTH: usize = {};\n\
         pub const DISPLAY_HEIGHT: usize = {};\n",
        config_path.display(),
        width,
        height,
    );
    let output = PathBuf::from(env::var("OUT_DIR").unwrap()).join("display_constants.rs");
    fs::write(output, generated).expect("failed to write generated display constants");
}
