name: google test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build dev container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: emulator-dev:latest
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Run build and tests inside container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspaces/YourEmulator -w /workspaces/YourEmulator emulator-dev:latest \
        bash -c "mkdir -p build && cd build && cmake . && make test
